title:            Jade McGough - @sailoremo
url:              http://jademcgough.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-49268083-1
timezone:         America/Los_Angeles
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
