title:            Jade McGough - @sailoremo
url:              http://jademcgough.github.io
permalink:        pretty
highlighter:      rouge
google_analytics: UA-49268083-1
timezone:         America/Los_Angeles
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-paginate
  - rdiscount
